### ISSUE TITLE
SparkStreaming-broadcast variable with rdd.sparkContext

### ISSUE THREAD

**Issue by sduchh** [acksin/acksin#182]
Generally, broadcast variable is used by JavaStreamingContext.sparkContext in driver, but code in https://github.com/apache/spark/blob/master/examples/src/main/scala/org/apache/spark/examples/streaming/RecoverableNetworkWordCount.scala in line 121 wrote like this:

val blacklist = WordBlacklist.getInstance(rdd.sparkContext)

I am confused that if  variable is broadcasted by rdd.sparkContext, is each executor pulls that variable each time or exactly once as rdd has its lifecycle?  What is the difference between these two ways when broadcasting variables? Please help me ,thanks.

**Comment by abhiyerra** [comment]
Wrong Project.
